/*
* Autogenerated header by File Header Comment extension - Donna Iwan
* File:       startup_page.dart
* Created on: Sat Mar 25 2023
* Author:     Tong Vu Than Dan
*
* Copyright (c) 2023 Tong Vu Than Dan
* Website:     dantopia.vn
*
* Description: This page is show when the app launch.
 */
import 'package:flutter/material.dart';

class StartUpPage extends StatelessWidget {
  const StartUpPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
