/*
* Autogenerated header by File Header Comment extension - Donna Iwan
* File:       step_provider.dart
* Created on: Wed Mar 22 2023
* Author:     Tong Vu Than Dan
*
* Copyright (c) 2023 Tong Vu Than Dan
* Website:     dantopia.vn
*
* Description: This file is create a provider for tracking current step of a technique
 */
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'step_provider.g.dart';

@riverpod
class CurrentStep extends _$CurrentStep {
  @override
  int build() => 0;

  void increase() => state = state + 1;

  void descrease() => state = state - 1;

  void update(int newValue) => state = newValue;
}
