/*
* Autogenerated header by File Header Comment extension - Donna Iwan
* File:       empty_project_body.dart
* Created on: Mon Mar 13 2023
* Author:     Tong Vu Than Dan
*
* Copyright (c) 2023 ${Dantopia}
* Website:     dantopia.vn
*
* Description: This file is shown when there is not any project in database
 */
import 'package:flutter/material.dart';

class EmptyProjectPageBody extends StatelessWidget {
  const EmptyProjectPageBody({super.key});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(left: 32, right: 16, top: 48),
      child: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const SizedBox(
              height: 48,
            ),
            Text(
              'Hello innovator,',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            Text(
              'time to innovate!',
              style: Theme.of(context).textTheme.titleMedium!.copyWith(
                    fontStyle: FontStyle.italic,
                  ),
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Image.asset('assets/images/time-to-innovate.png'),
              ],
            ),
            const SizedBox(
              height: 20,
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Material(
                  color: Colors.blue,
                  borderRadius: BorderRadius.circular(8.0),
                  child: SizedBox(
                    height: 180,
                    width: 240,
                    child: InkWell(
                      onTap: () {
                        //TODO - add action code for new idea
                      },
                      child: Image.asset(
                        'assets/images/new-idea.png',
                        fit: BoxFit.contain,
                        height: 100,
                        width: 100,
                      ),
                    ),
                  ),
                ),
                const SizedBox(
                  width: 20,
                ),
                Material(
                  color: Colors.orange,
                  borderRadius: BorderRadius.circular(8.0),
                  child: SizedBox(
                    height: 180,
                    width: 240,
                    child: InkWell(
                      onTap: () {
                        //TODO - add action code for problem solving
                      },
                      child: Image.asset(
                        'assets/images/problem-solving.png',
                        fit: BoxFit.contain,
                        height: 100,
                        width: 100,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
