/*
 * Autogenerated header by File Header Comment extension - Donna Iwan
 * File:       home_page.dart
 * Created on: Mon Mar 13 2023
 * Author:     Tong Vu Than Dan
 *
 * Copyright (c) 2023 Tong Vu Than Dan
 *
 * Description: the home page of the app.
 * This page will use flutter_adaptive_scaffold with AdaptiveLayout to enable the adaptivity.
 *  topNavigation: show only on web
    primaryNavigation: on show on desktop (macOS, Windows, web) and Tablet/iPad
    secondaryNavigation: not use
    bottomNavigation: only show on Mobile, small screen
    body: show on all screen size
    secondaryBody: show on all screen sizes except small screen 
    bodyRatio: 0.3, ratio between body and secondary body
 */
import 'package:flutter/material.dart';
import 'package:flutter_adaptive_scaffold/flutter_adaptive_scaffold.dart';
import 'package:innovation_hub/destination_items.dart';
import 'package:innovation_hub/empty_project_body.dart';

import 'demo_items.dart';

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: AdaptiveLayout(
        primaryNavigation: SlotLayout(
          config: {
            Breakpoints.medium: SlotLayout.from(
              key: const Key('primary-navi-medium'),
              inAnimation: AdaptiveScaffold.fadeIn,
              outAnimation: AdaptiveScaffold.fadeOut,
              builder: (context) => AdaptiveScaffold.standardNavigationRail(
                destinations: destinations.map(AdaptiveScaffold.toRailDestination).toList(),
                leading: Image.asset(
                  'assets/brand/logo-ihub@3x.png',
                  height: 48,
                ),
              ),
            ),
            Breakpoints.large: SlotLayout.from(
              key: const Key('primary-navi-large'),
              inAnimation: AdaptiveScaffold.fadeIn,
              outAnimation: AdaptiveScaffold.leftInOut,
              builder: (context) => AdaptiveScaffold.standardNavigationRail(
                extended: true,
                destinations: destinations.map(AdaptiveScaffold.toRailDestination).toList(),
                leading: Image.asset(
                  'assets/brand/logo-Innovation-HUB@3x.png',
                  height: 64,
                ),
              ),
            ),
          },
        ), // !primaryNavi
        body: SlotLayout(
          config: {
            Breakpoints.small: SlotLayout.from(
              key: const Key('Small Body'),
              builder: (_) => ListView.builder(
                itemCount: demoItems.length,
                itemBuilder: (_, index) => demoItems[index],
              ),
            ),
            Breakpoints.mediumAndUp: SlotLayout.from(
              key: const Key('Medium and up body'),
              builder: (_) => const EmptyProjectPageBody(),
              // builder: (_) => GridView.count(
              //   crossAxisCount: 2,
              //   children: demoItems,
              // ),
            ),
          },
        ),
      ),
    );
  }
}
