/*
* Autogenerated header by File Header Comment extension - Donna Iwan
* File:       theme.dart
* Created on: Mon Mar 13 2023
* Author:     Tong Vu Than Dan
*
* Copyright (c) 2023 ${Dantopia}
* Website:     dantopia.vn
*
* Description This file contains code defined theme of the app
 */

import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

const ColorScheme flexSchemeLight = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xff00296b),
  onPrimary: Color(0xffffffff),
  primaryContainer: Color(0xffa0c2ed),
  onPrimaryContainer: Color(0xff0e1014),
  secondary: Color(0xff5c5c95),
  onSecondary: Color(0xffffffff),
  secondaryContainer: Color(0xffc8dbf8),
  onSecondaryContainer: Color(0xff111214),
  tertiary: Color(0xffd26900),
  onTertiary: Color(0xffffffff),
  tertiaryContainer: Color(0xffffd270),
  onTertiaryContainer: Color(0xff14120a),
  error: Color(0xffb00020),
  onError: Color(0xffffffff),
  errorContainer: Color(0xfffcd8df),
  onErrorContainer: Color(0xff141213),
  background: Color(0xfff6f7f9),
  onBackground: Color(0xff090909),
  surface: Color(0xfff6f7f9),
  onSurface: Color(0xff090909),
  surfaceVariant: Color(0xffedeff4),
  onSurfaceVariant: Color(0xff121213),
  outline: Color(0xff565656),
  outlineVariant: Color(0xffa2a2a2),
  shadow: Color(0xff000000),
  scrim: Color(0xff000000),
  inverseSurface: Color(0xff101114),
  onInverseSurface: Color(0xfff5f5f5),
  inversePrimary: Color(0xff8dacdd),
  surfaceTint: Color(0xff00296b),
);
const ColorScheme flexSchemeDark = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xffb1cff5),
  onPrimary: Color(0xff111414),
  primaryContainer: Color(0xff3873ba),
  onPrimaryContainer: Color(0xffe8f1fc),
  secondary: Color(0xffc9cbfc),
  onSecondary: Color(0xff131314),
  secondaryContainer: Color(0xff535393),
  onSecondaryContainer: Color(0xffececf6),
  tertiary: Color(0xffffd270),
  onTertiary: Color(0xff14140c),
  tertiaryContainer: Color(0xffd26900),
  onTertiaryContainer: Color(0xfffff0df),
  error: Color(0xffcf6679),
  onError: Color(0xff140c0d),
  errorContainer: Color(0xffb1384e),
  onErrorContainer: Color(0xfffbe8ec),
  background: Color(0xff1a1c1e),
  onBackground: Color(0xffededed),
  surface: Color(0xff1a1c1e),
  onSurface: Color(0xffededed),
  surfaceVariant: Color(0xff23272b),
  onSurfaceVariant: Color(0xffdcdddd),
  outline: Color(0xffa1a1a1),
  outlineVariant: Color(0xff545454),
  shadow: Color(0xff000000),
  scrim: Color(0xff000000),
  inverseSurface: Color(0xfffafcfe),
  onInverseSurface: Color(0xff131313),
  inversePrimary: Color(0xff5b6878),
  surfaceTint: Color(0xffb1cff5),
);

const FlexSchemeData myFlexScheme = FlexSchemeData(
  name: 'Innovation HUB',
  description: 'Innovation theme, custom definition of all colors',
  light: FlexSchemeColor(
    primary: Color(0xfffc00b4),
    primaryContainer: Color(0xffef1df7),
    secondary: Color(0xffffc700),
    secondaryContainer: Color(0xffff9800),
    tertiary: Color(0xff063cf9),
    tertiaryContainer: Color(0xff2196f3),
    appBarColor: Color(0xffff9800),
    // appBarColor: Colors.transparent,
    error: Color(0xffb00020),
  ),
  dark: FlexSchemeColor(
    primary: Color(0xff9c27b0),
    primaryContainer: Color(0xff00325b),
    secondary: Color(0xffffeb3b),
    secondaryContainer: Color(0xffff5722),
    tertiary: Color(0xff3f51b5),
    tertiaryContainer: Color(0xff03a9f4),
    appBarColor: Color(0xffff5722),
    // appBarColor: Colors.transparent,
    error: Color(0xffcf6679),
  ),
);
