/*
* Autogenerated header by File Header Comment extension - Donna Iwan
* File:       new_project_page.dart
* Created on: Mon Mar 13 2023
* Author:     Tong Vu Than Dan
*
* Copyright (c) 2023 ${Dantopia}
* Website:     dantopia.vn
*
* Description: show new project page
 */
import 'package:flutter/material.dart';
import 'package:innovation_hub/utils/padding.dart';
import 'package:innovation_hub/utils/space.dart';

class NewProjectPage extends StatelessWidget {
  const NewProjectPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('New Project'),
      ),
      body: SingleChildScrollView(
        // controller: controller,
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 3 * defaultPadding),
          child: Column(
            children: [
              Card(
                child: Form(
                  child: Column(
                    children: [
                      TextFormField(),
                      Space.y(20),
                      TextFormField(),
                    ],
                  ),
                ),
              ),
              const Card(
                child: Text('Select tool'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
