// ignore_for_file: public_member_api_docs, sort_constructors_first
/*
* Autogenerated header by File Header Comment extension - Donna Iwan
* File:       prj_dashboard_view.dart
* Created on: Thu Mar 22 2023
* Author:     Tong Vu Than Dan
*
* Copyright (c) 2023 Tong Vu Than Dan
* Website:     dantopia.vn
*
* Description: This is the project dashboard tabview.
 */
import 'package:flutter/material.dart';
import 'package:innovation_hub/app/project/project_views/dashboard/component_container.dart';
import 'package:innovation_hub/app/project/project_views/dashboard/ideas_container.dart';
import 'package:innovation_hub/app/project/widgets/project_page_header.dart';
import 'package:innovation_hub/app/project/widgets/top_navi_view.dart';

class ProjectDashboardView extends StatelessWidget {
  const ProjectDashboardView({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.only(top: 12.0, left: 12, right: 12),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                TopNaviView(
                    title: Text(
                  'Dashboard',
                  style: Theme.of(context).textTheme.titleLarge,
                )),
                const ProjectPageHeader(),
                const SizedBox(height: 16),
                const ProjectComponentsContainer(),
                const SizedBox(height: 16),
                const IdeasContainer(),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
