// ignore_for_file: public_member_api_docs, sort_constructors_first
/*
* Autogenerated header by File Header Comment extension - Donna Iwan
* File:       prj_dashboard_view.dart
* Created on: Thu Mar 22 2023
* Author:     Tong Vu Than Dan
*
* Copyright (c) 2023 Tong Vu Than Dan
* Website:     dantopia.vn
*
* Description: This is the project dashboard tabview.
 */
import 'package:flutter/material.dart';
import 'package:flutter_adaptive_scaffold/flutter_adaptive_scaffold.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:innovation_hub/app/project/project_views/dashboard/component_container.dart';
import 'package:innovation_hub/app/project/widgets/project_page_header.dart';

import '../widgets/project_app_bar.dart';

class ProjectDashboardView extends ConsumerWidget {
  const ProjectDashboardView({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final isSmall = Breakpoints.small.isActive(context);
    final isMedium = Breakpoints.medium.isActive(context);
    return Scaffold(
      appBar: PreferredSize(
        preferredSize: Size.fromHeight(AppBar().preferredSize.height),
        child: ProjectPageAppBar(
          title: Text(
            'Project dashboard',
            overflow: TextOverflow.ellipsis,
            style: Theme.of(context).textTheme.titleLarge,
          ),
        ),
      ),
      body: LayoutBuilder(
        builder: (context, constraints) {
          return Column(
            children: [
              const ProjectPageHeader(),
              Expanded(
                child: GridView.count(
                  crossAxisCount: (isSmall || isMedium) ? 1 : 2,
                  padding: const EdgeInsets.only(
                    top: 48,
                    left: 32,
                    right: 32,
                  ),
                  children: [
                    SizedBox(
                      height: constraints.maxHeight * 0.3,
                      // width: constraints.maxWidth * 0.85,
                      child: const ProjectComponentsContainer(),
                    ),
                    SizedBox(
                      height: constraints.maxHeight * 0.3,
                      // width: constraints.maxWidth * 0.85,
                      child: const Placeholder(
                        child: Text('component attributes'),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          );
        },
      ),
    );
  }
}
