/*
* Autogenerated header by File Header Comment extension - Donna Iwan
* File:       padding.dart
* Created on: Mon Mar 13 2023
* Author:     Tong Vu Than Dan
*
* Copyright (c) 2023 ${Dantopia}
* Website:     dantopia.vn
*
* Description This file is defined some standard padding used in app 
 */
/// Standard paddiing used in app, default = 8.0
const double defaultPadding = 8.0;
