/*
* Autogenerated header by File Header Comment extension - Donna Iwan
* File:       space.dart
* Created on: Mon Mar 13 2023
* Author:     Tong Vu Than Dan
*
* Copyright (c) 2023 ${Dantopia}
* Website:     dantopia.vn
*
* Description This file is an ultility help to create space 
 */
import 'package:flutter/material.dart';

class Space {
  /// Create a space in x or width, with [x] value
  static Widget x(double x) => SizedBox(
        width: x,
      );

  /// Create a space in y or height, with [y] value
  static Widget y(double y) => SizedBox(
        height: y,
      );
}
