import 'dart:convert';

/*
* Autogenerated header by File Header Comment extension - Donna Iwan
* File:       attribute_model.dart
* Created on: Wed Mar 22 2023
* Author:     Tong Vu Than Dan
*
* Copyright (c) 2023 Tong Vu Than Dan
* Website:     dantopia.vn
*
* Description: Attribute of a component
 */
// ignore_for_file: public_member_api_docs, sort_constructors_first

class Attribute {
  String id;
  String name;
  String description;
  int importance;
  bool enabled;
  Attribute({
    required this.id,
    required this.name,
    required this.description,
    required this.importance,
    this.enabled = true,
  });

  Attribute copyWith({
    String? id,
    String? name,
    String? description,
    int? importance,
    bool? enabled,
  }) {
    return Attribute(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      importance: importance ?? this.importance,
      enabled: enabled ?? this.enabled,
    );
  }

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'id': id,
      'name': name,
      'description': description,
      'importance': importance,
      'enabled': enabled,
    };
  }

  factory Attribute.fromMap(Map<String, dynamic> map) {
    return Attribute(
      id: map['id'] as String,
      name: map['name'] as String,
      description: map['description'] as String,
      importance: map['importance'] as int,
      enabled: map['enabled'] as bool,
    );
  }

  String toJson() => json.encode(toMap());

  factory Attribute.fromJson(String source) => Attribute.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() {
    return 'Attribute(id: $id, name: $name, description: $description, importance: $importance, enabled: $enabled)';
  }

  @override
  bool operator ==(covariant Attribute other) {
    if (identical(this, other)) return true;

    return other.id == id && other.name == name && other.description == description && other.importance == importance && other.enabled == enabled;
  }

  @override
  int get hashCode {
    return id.hashCode ^ name.hashCode ^ description.hashCode ^ importance.hashCode ^ enabled.hashCode;
  }
}
